version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VERSION=1.2.9
    image: jirikadlec2/qc_eo4sd_frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS=/usr/local/src/qc-eo4sd/product_definitions
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WPS_DIR=/mnt/qc_tool_volume/wps
      - WORK_DIR=/mnt/qc_tool_volume/work
      - FRONTEND_PORT=8000
      - FRONTEND_DB_PATH=/mnt/qc_tool_volume/work/frontend.sqlite3
      - WPS_URL=http://qc_tool_wps:5000/wps
      - SHOW_LOGO=n
    volumes:
      - /home/jiri/github/qc-eo4sd:/usr/local/src/qc-eo4sd
      - /home/jiri/qc_tool/qc_tool_incoming:/mnt/qc_tool_incoming/incoming
      - /home/jiri/qc_tool/qc_tool_boundary:/mnt/qc_tool_boundary
      - /home/jiri/qc_tool/qc_tool_wps:/mnt/qc_tool_volume/wps
      - /home/jiri/qc_tool/qc_tool_work:/mnt/qc_tool_volume/work

  worker:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VERSION=1.2.9
    image: jirikadlec2/qc_eo4sd_frontend
    environment:
      - PRODUCT_DIRS=/usr/local/src/qc-eo4sd/product_definitions
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_volume/work
      - PG_HOST=qc_tool_postgis
      - PG_PORT=5432
      - PG_USER=qc_job
      - PG_DATABASE=qc_tool_db
      - LEAVE_SCHEMA=no
      - JOBDIR_EXIST_OK=no
      - LEAVE_JOBDIR=no
      - SHOW_LOGO=no
    networks:
      - qc_tool_network
    volumes:
      - /home/jiri/github/qc-eo4sd:/usr/local/src/qc-eo4sd
      - /home/jiri/qc_tool/qc_tool_incoming:/mnt/qc_tool_incoming/incoming
      - /home/jiri/qc_tool/qc_tool_boundary:/mnt/qc_tool_boundary
      - /home/jiri/qc_tool/qc_tool_wps:/mnt/qc_tool_volume/wps
      - /home/jiri/qc_tool/qc_tool_work:/mnt/qc_tool_volume/work
      - /home/jiri/qc_tool/qc_tool_submission:/mnt/qc_tool_submission

  postgis:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VERSION=1.2.9
    image: jirikadlec2/qc_eo4sd_frontend

networks:
  qc_tool_network:
    driver: bridge
