version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VERSION=1.2.6
    image: jirikadlec2/qc_eo4sd_frontend
    ports:
      - 80:8000
    environment:
      - PRODUCT_DIRS=/usr/local/src/qc-eo4sd/product_definitions
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - WPS_DIR=/mnt/qc_tool_volume/wps
      - WORK_DIR=/mnt/qc_tool_volume/work
      - FRONTEND_PORT=8000
      - FRONTEND_DB_PATH=/mnt/qc_tool_volume/work/frontend.sqlite3
      - WPS_URL=http://qc_tool_wps:5000/wps
      - SHOW_LOGO=no
    networks:
      - qc_tool_network
    volumes:
      - qc_tool_volume:/mnt/qc_tool_volume
      - qc_tool_frontend:/var/lib/qc_tool

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        - VERSION=1.2.6
    image: jirikadlec2/qc_eo4sd_worker
    environment:
      - PRODUCT_DIRS=/usr/local/src/qc-eo4sd/product_definitions
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_volume/work
      - PG_HOST=postgis
      - PG_PORT=5432
      - PG_USER=qc_job
      - PG_DATABASE=qc_tool_db
      - LEAVE_SCHEMA=no
      - JOBDIR_EXIST_OK=no
      - LEAVE_JOBDIR=no
      - SHOW_LOGO=no
    networks:
      - qc_tool_network
    volumes:
      - qc_tool_volume:/mnt/qc_tool_volume

  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
      args:
        - VERSION=1.2.6
    image: jirikadlec2/qc_eo4sd_postgis
    networks:
      - qc_tool_network

volumes:
  qc_tool_frontend:
    driver: local
  qc_tool_volume:
    driver: local

networks:
  qc_tool_network:
    driver: bridge